title: New Media and Technosemiosis modules@UPOL
logo: /assets/img/logo.png.png
description: Index for New Media and Technosemiosis modules@UPOL. 
author: Claudio Rodríguez
show_downloads: false
---
google_analytics:
theme: jekyll-theme-minimal
