title: New Media and Technosemiosis modules@UPOL
logo: /assets/img/logo.png.png
description: Index for New Media and Technosemiosis modules@UPOL. 
author: <a href="https://www.researchgate.net/profile/Claudio-Rodriguez-Higuera">Claudio Rodríguez</a>
show_downloads: false
---
google_analytics:
theme: jekyll-theme-minimal
