title: New Media and Technosemiosis modules@UPOL
logo: /assets/img/logo.png.png
description: Index for New Media and Technosemiosis modules@UPOL. This work was supported by the project Humanities going digital | Project no. 2020-1-CZ01-KA226-HE-094363. The European Commission's support for the production of this publication does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
